### ISSUE TITLE
Uncaught Promise rejection error when closing Share popup

### ISSUE THREAD

**Issue by hyphmongo** [seeden/react-facebook#136]
When using the Share component it will successfully bring up the popup window. But clicking the cross in top right of the window, without completing a share, throws an uncaught promise rejection error

```
<Share href="https://example.com"}>
  {({ handleClick, loading }) => (
    <Icon
      onClick={handleClick}
      disabled={loading}
    />
  )}
</Share>
```

![image](https://user-images.githubusercontent.com/36110276/61311154-b5299600-a7ed-11e9-9b3e-11071f8c9f7c.png)

**Comment by glenngijsberts** [comment]
From what I can see, the `ui` method, which is used for the share component, is returning `undefined` (coming from the fb api) instead of something like `{authResponse: undefined, status: "unknown"}` what they do with the `getTokenDetailWithProfile` method (used for the login component). It doesn't harm anything, but I created a PR that will hide the error if it's the `ui` method, since I am not sure if something else is depending on the check.
