### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by cgrewon** [seeden/react-facebook#206]
After install latest version, React is not defined issue was solved, but nothing is working.
Login, like, share... 
When I click Facebook login button, it is not working at all, no error messages or no popup dialog ..

**Comment by asi309** [comment]
@seeden I can look into this issue.

**Comment by NautHnil** [comment]
> After install latest version, React is not defined issue was solved, but nothing is working. Login, like, share... When I click Facebook login button, it is not working at all, no error messages or no popup dialog ..

I also got the same error. My website is frozen, laggy, and can't do anything. It's like being disabled website. :(

**Comment by JYachelini** [comment]
Wep, same here. Website frozen when I tried to login with facebook.

**Comment by omgdevopsteam** [comment]
same here my website freeze and became unresponsive ....

**Comment by barakrotshtein** [comment]
same here - it appears that an iframe is blocking anything from happening - is there any progress?

**Comment by adamgajzlerowicz** [comment]
Please fix this 🙏🏼

**Comment by seeden** [comment]
Freeze fixed in latest version 9.0.10
Here is working example https://codesandbox.io/s/agitated-fire-xvfzbd

Like, Comments and few other plugins are not working in EU when user is not logged in to facebook.
More details here:
https://developers.facebook.com/docs/plugins/like-button/

Changes to Social Plugins in the European Region

You may start to see some impact to Social Plugins due to an updated cookies consent prompt that will be shown to people using Facebook products in the European Region. We will no longer support the 'Like' and 'Comment' Social Plugins for European Region users, unless they are both 1) Logged into their Facebook account, and 2) have provided consent to the “App and Website Cookies” control. If both of these requirements are met, the user will be able to see and interact with plugins such as the 'Like' or 'Comment' button. If either of the requirements above are not met, the user will not be able to see the plugins.

The European Region is a specific list of countries including:
The European Union (EU): Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden
Non-EU Members, but in EEA-Only/EFTA or Customs Union: [EEA Only/EFTA] Iceland, Liechtenstein and Norway;Switzerland: [EU Customs Union] all Channel Islands, Isle of Man, Monaco; UK sovereign bases in Cyprus; [European Customs Union] Andorra, San Marino, Vatican City.
Non-EU members, but part of European Outermost Regions (OMR): Martinique, Mayotte, Guadeloupe, French Guiana, Réunion, Saint-Martin, Madeira, The Azores, Canary Islands.
United Kingdom (all British Isles)

**Comment by adamgajzlerowicz** [comment]
Just checked - It is working in Poland now. Thank you.
