### ISSUE TITLE
'react-facebook' does not contain an export named 'MessageUs'.

### ISSUE THREAD

**Issue by sznrbrt** [seeden/react-facebook#61]
'react-facebook' does not contain an export named 'MessageUs'.

# **Version**
"react-facebook": "^4.1.1",

# **Actual behaviour**
Clean project produces this error after installing the component. Other components such as like work neatly.

# **Steps to reproduce**
```
create-react-app test-app
npm install --save react-facebook
import FacebookProvider, { MessageUs } from 'react-facebook';
```

**Comment by tonypinkevych** [comment]
@sznrbrt 
They have rolled back to v4.1.1 where Message widgets haven't implemented yet.
Hope they will implement all of the features of message widgets in near future because this is very cool.

If you need to turn around with MessageUs widget you can do this thing:
Download the "MessageUs" component [there](https://github.com/seeden/react-facebook/blob/master/src/MessageUs.jsx).

And than:
```jsx
import React from 'react';
import FacebookProvider, { Parser } from 'react-facebook';
import MessageUs from './MessageUs';

import { FB_APP_ID, FB_PAGE_ID } from './constants';

const FBMessageUs = () => (
  <FacebookProvider appId={FB_APP_ID}>
    <MessageUs appId={FB_APP_ID} pageId={FB_PAGE_ID} />
  </FacebookProvider>
);

export default FBMessageUs;
```

**Comment by sznrbrt** [comment]
Thanks for the info! Yeah, this is an awesome project!

However, for now ended up using something like this for the browser:

>       <a href="https://www.messenger.com/t/<page-id>/"
>       className="fb-message-white"
>       target="_blank">
>       <i></i> Message Us</a>

**Comment by seeden** [comment]
it is fixed in the last release
